/usr/local/bin/python -m pip install asttokens==2.2.1
/usr/local/bin/python -m pip install backcall==0.2.0
/usr/local/bin/python -m pip install backports.functools-lru-cache==1.6.4
/usr/local/bin/python -m pip install brotlipy==0.7.0
/usr/local/bin/python -m pip install certifi==2022.12.7
/usr/local/bin/python -m pip install cffi==1.15.1
/usr/local/bin/python -m pip install charset-normalizer==2.1.1
/usr/local/bin/python -m pip install colorama==0.4.6
/usr/local/bin/python -m pip install comm==0.1.2
/usr/local/bin/python -m pip install conda==22.11.1
/usr/local/bin/python -m pip install conda-package-handling==2.0.2
/usr/local/bin/python -m pip install conda_package_streaming==0.7.0
/usr/local/bin/python -m pip install cryptography==38.0.4
/usr/local/bin/python -m pip install debugpy==1.6.4
/usr/local/bin/python -m pip install decorator==5.1.1
/usr/local/bin/python -m pip install entrypoints==0.4
/usr/local/bin/python -m pip install executing==1.2.0
/usr/local/bin/python -m pip install idna==3.4
/usr/local/bin/python -m pip install ipykernel==6.19.4
/usr/local/bin/python -m pip install ipython==8.7.0
/usr/local/bin/python -m pip install jedi==0.18.2
/usr/local/bin/python -m pip install jupyter_client==7.4.8
/usr/local/bin/python -m pip install jupyter_core==5.1.0
/usr/local/bin/python -m pip install libmambapy==1.1.0
/usr/local/bin/python -m pip install mamba==1.1.0
/usr/local/bin/python -m pip install matplotlib-inline==0.1.6
/usr/local/bin/python -m pip install nest-asyncio==1.5.6
/usr/local/bin/python -m pip install numpy==1.24.0
/usr/local/bin/python -m pip install packaging==22.0
/usr/local/bin/python -m pip install pandas==1.5.2
/usr/local/bin/python -m pip install parso==0.8.3
/usr/local/bin/python -m pip install pexpect==4.8.0
/usr/local/bin/python -m pip install pickleshare==0.7.5
/usr/local/bin/python -m pip install pip==22.3.1
/usr/local/bin/python -m pip install platformdirs==2.6.0
/usr/local/bin/python -m pip install pluggy==1.0.0
/usr/local/bin/python -m pip install prompt-toolkit==3.0.36
/usr/local/bin/python -m pip install psutil==5.9.4
/usr/local/bin/python -m pip install ptyprocess==0.7.0
/usr/local/bin/python -m pip install pure-eval==0.2.2
/usr/local/bin/python -m pip install pycosat==0.6.4
/usr/local/bin/python -m pip install pycparser==2.21
/usr/local/bin/python -m pip install Pygments==2.13.0
/usr/local/bin/python -m pip install pyOpenSSL==22.1.0
/usr/local/bin/python -m pip install PySocks==1.7.1
/usr/local/bin/python -m pip install python-dateutil==2.8.2
/usr/local/bin/python -m pip install pytz==2022.7
/usr/local/bin/python -m pip install pyzmq==24.0.1
/usr/local/bin/python -m pip install requests==2.28.1
/usr/local/bin/python -m pip install ruamel.yaml==0.17.21
/usr/local/bin/python -m pip install ruamel.yaml.clib==0.2.7
/usr/local/bin/python -m pip install setuptools==65.6.3
/usr/local/bin/python -m pip install six==1.16.0
/usr/local/bin/python -m pip install stack-data==0.6.2
/usr/local/bin/python -m pip install toolz==0.12.0
/usr/local/bin/python -m pip install tornado==6.2
/usr/local/bin/python -m pip install tqdm==4.64.1
/usr/local/bin/python -m pip install traitlets==5.8.0
/usr/local/bin/python -m pip install urllib3==1.26.13
/usr/local/bin/python -m pip install wcwidth==0.2.5
/usr/local/bin/python -m pip install wheel==0.38.4
/usr/local/bin/python -m pip install zstandard==0.19.0